inherit_gem:
  gc_ruboconfig: rubocop.yml

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 2

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

RSpec/ImplicitBlockExpectation:
  Enabled: false
