name: tests
on: push

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_NO-CACHE: 'true'
      BUNDLE_JOBS: '4'
      BUNDLE_RETRY: '3'
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run specs
      run: bundle exec rspec --format progress --format RSpec::Github::Formatter -o /tmp/rspec.xml
    - name: Rubocop
      run: bundle exec rubocop --extra-details --display-style-guide --parallel --force-exclusion
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: /tmp/ci_artifacts/
