name: tests
on: push

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
        - '2.7'
        - '3.0'
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run specs
      # todo update test globbing and add rspec-github gem for the formatter
      run: |-
        circleci tests glob "spec/**/*_spec.rb"
        bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) --profile --format progress --format RSpec::Github::Formatter -o /tmp/ci_artifacts/rspec.xml
    - name: Rubocop
      run: bundle exec rubocop --extra-details --display-style-guide --parallel --force-exclusion
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: /tmp/ci_artifacts/
